apiVersion: v1
kind: Pod
metadata:
  name: bso-training-webapp
spec:
  containers:
  - name: bso-training-webapp
    image: ghcr.io/izual750/bso-training-webapp:latest
    ports:
    - containerPort: 9000
