apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: bso-training-webapp-rs
  labels:
    app: bso-training
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bso-training
  template:
    metadata:
      labels:
        app: bso-training
    spec:
      containers:
        - name: bso-training-webapp
          image: ghcr.io/izual750/bso-training-webapp:1.2
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: 6379
            - name: REDIS_PASSWORD
              value: simplewebapp
          ports:
            - containerPort: 8080
              protocol: TCP
