apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: bso-training-webapp-rs
  labels:
    app: bso-training
    tier: frontend
spec:
  # Modify this number to scale your application
  replicas: 3
  selector:
    matchLabels:
      app: bso-training
  template:
    metadata:
      labels:
        app: bso-training
    spec:
      containers:
      - name: bso-training-webapp
        image: ghcr.io/izual750/bso-training-webapp:latest
        ports:
        - containerPort: 9000
          protocol: TCP