apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-webapp
  template:
    metadata:
      labels:
        app: php-webapp
    spec:
      containers:
        - name: webapp
          image: ghcr.io/izual750/bso-training-webapp:1.2.2
          env:
          - name: REDIS_HOST
            value: "redis-sentinel"
          - name: REDIS_PORT
            value: 6379
          - name: REDIS_PASSWORD
            value: "simplewebapp"
          ports:
            - containerPort: 8080